### ISSUE TITLE
Example code won't work

### ISSUE THREAD

**Issue by sscarduzio** [molekilla/hapi-passport-saml#19]
```js

const hapi = require('hapi');

const server = new hapi.Server({
  port: 9999
})

const idpCert = '...';
const decryptionCert = '...';
const samlOptions = {
  // passport saml settings
  saml: {
    callbackUrl: 'http://localhost/api/sso/v1/assert',
    logoutCallbackUrl: 'http://localhost/api/sso/v1/notifylogout',
    logoutUrl: 'https://my-idp.samlidp.io/saml2/idp/SingleLogoutService.php',
    host: 'localhost',
    protocol: 'http',
    entryPoint: 'https://my-idp.samlidp.io/saml2/idp/SSOService.php',
    // Service Provider Private Key
    decryptionPvk: null, //fs.readFileSync(__dirname + '/private.key').toString(),
    // IdP Public Key
    cert: idpCert,
    issuer: 'my-saml'
  },
  // hapi-passport-saml settings
  config: {
    // Service Provider Public Key
    decryptionCert,
    // Plugin Routes
    routes: {
      // SAML Metadata
      metadata: {
        path: '/api/sso/v1/metadata.xml',
      },
      // SAML Assertion
      assert: {
        path: '/api/sso/v1/assert',
      },
    },
    assertHooks: {
      // Assertion Response Hook
      // Use this to add any specific props for your business
      // or appending to existing cookie
      // or make use of the RelayState
      onResponse: (profile, request, h) => {
        if (request.payload.RelayState)
          return h.redirect(request.payload.RelayState);
        else
          return h.response();
      },
    }
  }
};

const serverPlugins = [{
  register: require('hapi-passport-saml'),
  options: samlOptions,
}];

// Internal cookie settings
const schemeOpts = {
  password: '14523695874159852035.0',
  isSecure: false,
  isHttpOnly: false,
  ttl: 3600,
}
server.register(serverPlugins, function (err) {
  server.auth.strategy('single-sign-on', 'saml', schemeOpts);
  server.register(controllers, {
    routes: {
      prefix: '/api'
    }
  }, function () {
    if (!module.parent) {
      server.start(function () {
        console.log('Server started at port ' + server.info.port);
      });
    }
  });

});

```

Won't even start, and gives the following error:

```
$ node testAuth.js
(node:7881) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Invalid register options "value" must be an object
    at new AssertionError (internal/assert.js:269:11)
    at Object.exports.assert (/me/kibana_plugin/kibana-extra/readonlyrest_kbn/node_modules/hoek/lib/index.js:524:11)
    at Object.exports.apply (/me/kibana_plugin/kibana-extra/readonlyrest_kbn/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/me/kibana_plugin/kibana-extra/readonlyrest_kbn/node_modules/hapi/lib/server.js:379:26)
    at Object.<anonymous> (/me/kibana_plugin/kibana-extra/readonlyrest_kbn/testAuth.js:69:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:7881) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7881) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by molekilla** [comment]
Hi Simone, this is for the latest Hapi version, be sure to tag previous non
Hapi 17

**Comment by sscarduzio** [comment]
Hi Rogelio, I'm using the new API.
```
$ grep hapi  package.json
    "hapi": "^17.0.18",
    "hapi-auth-cookie": "9.1.0",
    "hapi-passport-saml": "2.0.0",
```

**Comment by molekilla** [comment]
Oh  I see. The new API was commited by a community user, most likely the
sample code needs improvement.

**Comment by sscarduzio** [comment]
Yes, BTW also the example project is old

**Comment by JbIPS** [comment]
I copy-pasted my sample project index (removed all non-related lines), that should work but tell me if it isn't :wink:
